/** Every action the policy can decide. Adding one requires a policy decision. */
export const ACTIONS = [
  'project:read',
  'project:rename',
  'project:delete',
  'folder:create',
  'folder:rename',
  'folder:delete',
  'folder:reorder',
  'task:create',
  'task:read',
  'task:rename',
  'task:delete',
  'task:move',
  'task:reorder',
  'tab:create',
  'tab:rename',
  'tab:delete',
  'tab:reorder',
  'tab:write',
  'share:read',
  'share:create',
  'share:revoke',
  'share:update',
  'export:run',
  'workspace:list-projects',
  'workspace:create-project',
  'workspace:import',
  'workspace:search',
  'plan:read',
  'plan:rename',
  'plan:retime',
  'plan:delete',
  'epic:create',
  'epic:rename',
  'epic:delete',
  'epic:reorder',
  'epic:bind',
  'feature:create',
  'feature:rename',
  'feature:estimate',
  'feature:delete',
  'feature:place',
  'feature:depend',
  'item:create',
  'item:rename',
  'item:estimate',
  'item:describe',
  'item:delete',
  'item:place',
  'item:link',
  'workspace:list-plans',
  'workspace:create-plan',
] as const

/** Something a principal may attempt. */
export type Action = (typeof ACTIONS)[number]
