export { emptyDocument, type DocumentJson } from './entities/document.js'
export { NO_PROGRESS, type Progress } from './entities/progress.js'
export type { Tab } from './entities/tab.js'
export type { TaskDocument } from './entities/task.js'
export type { Folder } from './entities/folder.js'
export type { ShareLink } from './entities/share-link.js'
export type { ProjectManifest, TaskEntry } from './entities/manifest.js'
export type { ProjectStore } from './ports/project-store.js'
export type { ServiceContext } from './services/context.js'
export { FsProjectStore, type FsProjectStoreOptions } from './storage/fs-project-store.js'
export { ShareIndex, type TokenOwner } from './storage/share-index.js'
export { manifestFile, projectDir, projectsDir, taskFile, tasksDir } from './storage/paths.js'
